#!/usr/bin/env bash
# coding workflow 任务 4ea44bcf-780b-41e2-b150-299f1a7a5bd7 的真人 QA 验收命令固化（审计 #9）：QA 与独立裁判通过后由 runner 生成，勿手改
# 场景按 spec 要求自己造数据，CI 空库可复现；失败即回归。
set -euo pipefail
# 真 Brain 写入必须显式授权，并核对本机测试容器。
if ! node "$(dirname "${BASH_SOURCE[0]}")/../lib/smoke-production-guard.mjs" "${BRAIN_URL:-http://localhost:5221}"; then
  exit 0
fi
BRAIN_URL="${BRAIN_URL:-http://localhost:5221}"

echo "== T-1（对应 Q-1）"
R=$(openssl rand -hex 4); T="QA-cat-bogus-$R"; RESP=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"workflow_bogus\",\"topic\":\"$T\",\"decision\":\"非法类别探针\"}"); echo "$RESP"; BODY=$(echo "$RESP" | sed '$d'); CODE=$(echo "$RESP" | tail -1); test "$CODE" = 400 && echo "$BODY" | jq -e '.success==false and (.allowed_categories|length==13) and (.allowed_categories|index("decision")!=null) and (.allowed_categories|index("judgment")!=null) and (.allowed_categories|index("testing")!=null) and (.error|test("decision")) and (.error|test("judgment"))' && ! echo "$BODY" | grep -Eq 'decisions_category_chk|violates|relation|check constraint' && curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?limit=200' | jq -e --arg t "$T" '.success==true and ([.data[]|select(.topic==$t)]|length==0)' && echo "Q1 PASS topic=$T"

echo "== T-2（对应 Q-2）"
R=$(openssl rand -hex 4); LONG=$(printf 'a%.0s' $(seq 1 10000)); FAIL=0; i=0; for CAT in '"Decision"' '1' '["decision"]' "\"$LONG\""; do i=$((i+1)); T="QA-cat-q2-$i-$R"; RESP=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":$CAT,\"topic\":\"$T\",\"decision\":\"Q2探针\"}"); BODY=$(echo "$RESP" | sed '$d'); CODE=$(echo "$RESP" | tail -1); echo "case$i code=$CODE body=$(echo "$BODY" | head -c 160)"; if [ "$CODE" != 400 ] || ! echo "$BODY" | jq -e '.success==false and (.allowed_categories|length==13)' >/dev/null || echo "$BODY" | grep -Eq 'decisions_category_chk|violates|relation|check constraint|value too long'; then FAIL=1; fi; done; curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?limit=200' | jq -e --arg r "$R" '[.data[]|select(.topic|startswith("QA-cat-q2-") and endswith($r))]|length==0' && test $FAIL = 0 && echo "Q2 PASS R=$R"

echo "== T-3（对应 Q-3）"
R=$(openssl rand -hex 4); FAIL=0; for V in none empty null; do T="QA-cat-default-$V-$R"; case $V in none) B="{\"topic\":\"$T\",\"decision\":\"不带类别\"}";; empty) B="{\"topic\":\"$T\",\"decision\":\"空类别\",\"category\":\"\"}";; null) B="{\"topic\":\"$T\",\"decision\":\"null类别\",\"category\":null}";; esac; RESP=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "$B"); BODY=$(echo "$RESP" | sed '$d'); CODE=$(echo "$RESP" | tail -1); echo "$V code=$CODE category=$(echo "$BODY" | jq -r .data.category) id=$(echo "$BODY" | jq -r .data.id)"; if [ "$CODE" != 201 ] || ! echo "$BODY" | jq -e '.data.category=="decision" and (.data.id|type=="string" and length>0)' >/dev/null; then FAIL=1; fi; done; curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?category=decision&limit=200' | jq -e --arg r "$R" '[.data[]|select(.topic|startswith("QA-cat-default-") and endswith($r))]|length==3' && test $FAIL = 0 && echo "Q3 PASS R=$R"

echo "== T-4（对应 Q-4）"
R=$(openssl rand -hex 4); T="QA-cat-valid-$R"; RESP=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"decision\",\"topic\":\"$T\",\"decision\":\"合法类别\"}"); echo "$RESP" | head -c 300; echo; CODE=$(echo "$RESP" | tail -1); test "$CODE" = 201 && echo "$RESP" | sed '$d' | jq -e '.data.category=="decision"' && G=$(curl -q -s -w '\n%{http_code}' '"$BRAIN_URL"/api/brain/strategic-decisions?category=decision&limit=200') && test "$(echo "$G" | tail -1)" = 200 && echo "$G" | sed '$d' | jq -e --arg t "$T" '[.data[]|select(.topic==$t)] as $m | ($m|length==1) and $m[0].category=="decision" and $m[0].status=="active"' && echo "Q4 PASS topic=$T"

echo "== T-5（对应 Q-5）"
R=$(openssl rand -hex 4); T="判定点[qa000000#1]: QA-$R"; B=$(jq -nc --arg t "$T" '{category:"judgment",topic:$t,decision:"所选方法: x｜候选: y",reason:"依据: z",made_by:"system",author:"coding-workflow",source_ref:"coding-workflow:qa"}'); RESP=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "$B"); echo "$RESP" | head -c 300; echo; test "$(echo "$RESP" | tail -1)" = 201 && curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?category=judgment&limit=1000' | jq -e --arg t "$T" '[.data[]|select(.topic==$t)] as $m | ($m|length==1) and $m[0].made_by=="system" and $m[0].author=="coding-workflow" and $m[0].category=="judgment"' && echo "Q5 PASS topic=$T"

echo "== T-6（对应 Q-7）"
R=$(openssl rand -hex 4); T1="QA-madeby-$R"; T2="QA-prio-$R"; R1=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"judgment\",\"topic\":\"$T1\",\"decision\":\"旧 shape 探针\",\"made_by\":\"ai\"}"); R2=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"topic\":\"$T2\",\"decision\":\"优先级探针\",\"priority\":\"P9\"}"); echo "$R1"; echo "$R2"; test "$(echo "$R1" | tail -1)" = 400 && test "$(echo "$R2" | tail -1)" = 400 && echo "$R1" | sed '$d' | jq -e '.success==false and .allowed_made_by==["user","cecelia","system"]' && echo "$R2" | sed '$d' | jq -e '.success==false and .allowed_priorities==["P0","P1","P2","P3"]' && ! printf '%s\n%s' "$R1" "$R2" | grep -Eq 'check constraint|violates' && curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?limit=200' | jq -e --arg a "$T1" --arg b "$T2" '[.data[]|select(.topic==$a or .topic==$b)]|length==0' && echo "Q7 PASS R=$R"

echo "== T-8（对应 Q-6）"
R=$(openssl rand -hex 4); T="QA-cat-dup-$R"; TB="QA-cat-dupbad-$R"; C1=$(curl -q -s -o /dev/null -w '%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"decision\",\"topic\":\"$T\",\"decision\":\"重复提交\"}"); C2=$(curl -q -s -o /dev/null -w '%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"decision\",\"topic\":\"$T\",\"decision\":\"重复提交\"}"); B1=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"workflow_bogus\",\"topic\":\"$TB\",\"decision\":\"重复非法\"}"); B2=$(curl -q -s -w '\n%{http_code}' -X POST "$BRAIN_URL"/api/brain/strategic-decisions -H 'content-type: application/json' -d "{\"category\":\"workflow_bogus\",\"topic\":\"$TB\",\"decision\":\"重复非法\"}"); echo "valid: $C1 $C2"; echo "bad1: $(echo "$B1" | tail -1) bad2: $(echo "$B2" | tail -1) same_body=$([ "$B1" = "$B2" ] && echo yes || echo no)"; test "$C1" = 201 && test "$C2" = 201 && test "$(echo "$B1" | tail -1)" = 400 && test "$B1" = "$B2" && curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?category=decision&limit=200' | jq -e --arg t "$T" '[.data[]|select(.topic==$t)]|length==2' && curl -q -s '"$BRAIN_URL"/api/brain/strategic-decisions?limit=200' | jq -e --arg t "$TB" '[.data[]|select(.topic==$t)]|length==0' && echo "Q6 PASS R=$R"

echo "PASS: cw-4ea44bcf-qa-smoke.sh"
