-- Migration 115: Add system_reports table for 48h periodic reports
-- Stores system briefing reports generated by Brain/Cortex

CREATE TABLE IF NOT EXISTS system_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  content JSONB NOT NULL DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_system_reports_created_at ON system_reports (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_reports_type_created ON system_reports (type, created_at DESC);

INSERT INTO schema_version (version, description)
VALUES ('115', 'Add system_reports table for 48h periodic reports')
ON CONFLICT (version) DO NOTHING;
