import { Router } from 'express';
import pool from '../db.js';
import { createTask, updateTask } from '../actions.js';
import { routeTask, TASK_TYPE_AGENT_MAP } from '../tick.js';
import { identifyWorkType, getTaskLocation, routeTaskCreate, getValidTaskTypes, LOCATION_MAP, diagnoseKR } from '../task-router.js';
import { getTaskWeights } from '../task-weight.js';
import { classifyLearningType } from './shared.js';
import { publishTaskCreated } from '../events/taskEvents.js';
import { getQuarantinedTasks, getQuarantineStats, releaseTask, quarantineTask, QUARANTINE_REASONS, REVIEW_ACTIONS } from '../quarantine.js';
import { triggerCeceliaRun, checkCeceliaRunAvailable } from '../executor.js';

const router = Router();

// ==================== Task Feedback & Status API (Phase 4b) ====================

/**
 * POST /api/brain/tasks/:task_id/feedback
 * 接收 Engine 上传的任务执行反馈
 */
router.post('/tasks/:task_id/feedback', async (req, res) => {
  try {
    const { task_id } = req.params;

    // Support two formats:
    // 1. Flat: { status, summary, issues_found, next_steps_suggested, ... }
    // 2. Wrapped: { feedback: { summary, issues_found, next_steps_suggested, ... } }
    //    (generated by packages/engine/skills/dev/scripts/upload-feedback.sh)
    const body = req.body.feedback && typeof req.body.feedback === 'object'
      ? req.body.feedback
      : req.body;

    const {
      status: rawStatus,
      summary,
      metrics,
      artifacts,
      issues,
      learnings,
      issues_found,
      next_steps_suggested,
    } = body;

    // status is optional — default to 'completed' for compatibility with
    // generate-feedback-report.sh which does not include a status field.
    const status = rawStatus || 'completed';

    // summary is still required
    if (!summary) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        code: 'MISSING_FIELD',
        required: ['summary']
      });
    }

    // Validate status value
    if (!['completed', 'failed'].includes(status)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid status value',
        code: 'INVALID_STATUS',
        allowed: ['completed', 'failed']
      });
    }

    // Check if task exists (also fetch goal_id for suggestion metadata)
    const taskResult = await pool.query(
      'SELECT id, status, goal_id FROM tasks WHERE id = $1',
      [task_id]
    );
    if (taskResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Task not found',
        code: 'TASK_NOT_FOUND'
      });
    }

    const task = taskResult.rows[0];

    // Validate task status (must be in_progress or completed to receive feedback)
    if (!['in_progress', 'completed', 'failed'].includes(task.status)) {
      return res.status(400).json({
        success: false,
        error: 'Task must be in_progress, completed, or failed to receive feedback',
        code: 'INVALID_TASK_STATUS',
        current_status: task.status
      });
    }

    // Generate unique feedback ID
    const feedbackId = crypto.randomUUID();
    const receivedAt = new Date().toISOString();

    // Construct feedback object
    const feedback = {
      id: feedbackId,
      status,
      summary,
      ...(metrics && { metrics }),
      ...(artifacts && { artifacts }),
      ...(issues && { issues }),
      ...(learnings && { learnings }),
      ...(issues_found && { issues_found }),
      ...(next_steps_suggested && { next_steps_suggested }),
      received_at: receivedAt
    };

    // Append to feedback array and increment count
    await pool.query(`
      UPDATE tasks
      SET
        feedback = feedback || $1::jsonb,
        feedback_count = feedback_count + 1,
        updated_at = NOW()
      WHERE id = $2
    `, [JSON.stringify([feedback]), task_id]);

    // ── Magentic-One: Agent Findings → Suggestions (best-effort) ────────────
    // Convert issues_found and next_steps_suggested into suggestions table entries
    // so that Suggestion Triage and Goal Outer Loop can act on agent findings.
    let suggestionsCreated = 0;
    try {
      const suggestionItems = [
        ...((Array.isArray(issues_found) ? issues_found : []).map(content => ({
          content: String(content),
          suggestion_type: 'issue',
          priority_score: 0.75,
        }))),
        ...((Array.isArray(next_steps_suggested) ? next_steps_suggested : []).map(content => ({
          content: String(content),
          suggestion_type: 'next_step',
          priority_score: 0.55,
        }))),
      ];

      for (const item of suggestionItems) {
        // Idempotency: skip if a suggestion with the same feedback_id and content already exists
        const existing = await pool.query(
          `SELECT id FROM suggestions
           WHERE source = 'agent_feedback'
             AND metadata->>'feedback_id' = $1
             AND content = $2
           LIMIT 1`,
          [feedbackId, item.content]
        );
        if (existing.rows.length > 0) continue;

        await pool.query(
          `INSERT INTO suggestions
             (content, priority_score, source, agent_id, suggestion_type,
              target_entity_type, target_entity_id, metadata)
           VALUES ($1, $2, 'agent_feedback', 'dev', $3, 'task', $4, $5)`,
          [
            item.content,
            item.priority_score,
            item.suggestion_type,
            task_id,
            JSON.stringify({
              feedback_id: feedbackId,
              task_id,
              goal_id: task.goal_id || null,
            }),
          ]
        );
        suggestionsCreated++;
      }

      if (suggestionsCreated > 0) {
        console.log(`[feedback] Task ${task_id}: created ${suggestionsCreated} suggestion(s) from agent findings`);
      }
    } catch (suggErr) {
      // Suggestions creation is best-effort — log but don't fail the request
      console.error(`[feedback] Suggestions creation failed (non-fatal): ${suggErr.message}`);
    }
    // ────────────────────────────────────────────────────────────────────────

    res.json({
      success: true,
      task_id,
      feedback_id: feedbackId,
      received_at: receivedAt,
      suggestions_created: suggestionsCreated,
    });
  } catch (err) {
    console.error('Failed to store feedback:', err);
    res.status(500).json({
      success: false,
      error: 'Failed to store feedback',
      code: 'DATABASE_ERROR',
      details: err.message
    });
  }
});

/**
 * POST /api/brain/learnings-received
 *
 * LEARNINGS 路由入口：dev workflow 将 LEARNINGS.md 提取内容发送到此处。
 * 丘脑分拣：
 *   - issues_found（已知 bug）→ 创建 fix task（任务线）
 *   - next_steps_suggested（经验/预防措施）→ 写 learnings 表（成长线 → 反刍 → NotebookLM）
 *
 * 新增（migration 151）：自动填充 source_branch、source_pr、repo、learning_type 字段
 *   - source_branch: 来自 branch_name
 *   - source_pr: 来自 pr_number
 *   - repo: 来自 payload.repo（默认 'cecelia'）
 *   - learning_type: 异步 Haiku 分类（best-effort，失败不影响插入）
 */

/**
 * 使用 fact_extractor (Haiku) 对 learning 内容进行分类。
 * 返回 5 种类型之一，或 null（分类失败时）。
 * @param {string} content
 * @returns {Promise<string|null>}
 */

router.post('/learnings-received', async (req, res) => {
  try {
    const {
      issues_found = [],
      next_steps_suggested = [],
      branch_name,
      pr_number,
      task_id,
      repo = 'cecelia',
    } = req.body;

    const results = { tasks_created: [], learnings_inserted: [] };

    // 1. issues_found → 创建 fix task（任务线）
    for (const issue of issues_found) {
      if (!issue || typeof issue !== 'string') continue;
      try {
        const taskResult = await createTask({
          title: `Fix: ${issue.slice(0, 120)}`,
          description: `来源：LEARNINGS_RECEIVED（分支 ${branch_name || 'unknown'}${pr_number ? ` / PR #${pr_number}` : ''}）\n\n${issue}`,
          task_type: 'dev',
          priority: 'P1',
          trigger_source: 'learnings_received',
          payload: { branch_name, pr_number, task_id, source: 'learnings_received' },
        });
        if (taskResult?.task?.id) {
          results.tasks_created.push(taskResult.task.id);
        }
      } catch (taskErr) {
        console.warn(`[learnings-received] createTask failed for issue: ${taskErr.message}`);
      }
    }

    // 2. next_steps_suggested → 写 learnings 表（成长线）
    // 先批量插入（source_branch/source_pr/repo 立即填充），learning_type 异步补填
    const insertedItems = [];
    for (const step of next_steps_suggested) {
      if (!step || typeof step !== 'string') continue;
      try {
        const title = step.slice(0, 120);
        const { rows } = await pool.query(
          `INSERT INTO learnings
             (title, category, content, trigger_source, trigger_event, digested,
              source_branch, source_pr, repo)
           VALUES ($1, 'dev_experience', $2, 'dev_workflow', 'learnings_received', false,
                   $3, $4, $5)
           RETURNING id`,
          [title, step, branch_name || null, pr_number ? String(pr_number) : null, repo]
        );
        if (rows[0]?.id) {
          results.learnings_inserted.push(rows[0].id);
          insertedItems.push({ id: rows[0].id, content: step });
        }
      } catch (dbErr) {
        console.warn(`[learnings-received] learnings INSERT failed: ${dbErr.message}`);
      }
    }

    // 3. 异步分类 learning_type（best-effort，不阻塞响应）
    if (insertedItems.length > 0) {
      Promise.all(insertedItems.map(async ({ id, content }) => {
        const learningType = await classifyLearningType(content);
        if (learningType) {
          await pool.query(
            `UPDATE learnings SET learning_type = $1 WHERE id = $2`,
            [learningType, id]
          ).catch(err => console.warn(`[learnings-received] learning_type update failed for ${id}: ${err.message}`));
        }
      })).catch(() => {}); // 整体失败静默处理
    }

    // 3. 触发丘脑事件（记录、可见性）
    try {
      await pool.query(
        `INSERT INTO cecelia_events (event_type, source, payload) VALUES ($1, $2, $3)`,
        ['learnings_received', 'dev_workflow', JSON.stringify({
          issues_count: issues_found.length,
          steps_count: next_steps_suggested.length,
          tasks_created: results.tasks_created.length,
          learnings_inserted: results.learnings_inserted.length,
          branch_name,
          pr_number,
        })]
      );
    } catch (evtErr) {
      console.warn('[learnings-received] event log failed (non-fatal):', evtErr.message);
    }

    console.log(`[learnings-received] issues=${issues_found.length} → ${results.tasks_created.length} tasks, steps=${next_steps_suggested.length} → ${results.learnings_inserted.length} learnings`);

    res.json({
      success: true,
      tasks_created: results.tasks_created.length,
      learnings_inserted: results.learnings_inserted.length,
      task_ids: results.tasks_created,
      learning_ids: results.learnings_inserted,
    });
  } catch (err) {
    console.error('[learnings-received] failed:', err);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * PATCH /api/brain/tasks/:task_id
 * 更新任务状态（Engine 调用）
 */
router.patch('/tasks/:task_id', async (req, res) => {
  try {
    const { task_id } = req.params;
    const { status, custom_props } = req.body;

    // Require at least one of status or custom_props
    if (!status && !custom_props) {
      return res.status(400).json({
        success: false,
        error: 'Missing required field: status or custom_props',
        code: 'MISSING_FIELD'
      });
    }

    // Validate status value if provided
    if (status) {
      const allowedStatuses = ['in_progress', 'completed', 'failed'];
      if (!allowedStatuses.includes(status)) {
        return res.status(400).json({
          success: false,
          error: 'Invalid status value',
          code: 'INVALID_STATUS',
          allowed: allowedStatuses
        });
      }
    }

    // Validate custom_props is a plain object if provided
    if (custom_props !== undefined && (typeof custom_props !== 'object' || Array.isArray(custom_props) || custom_props === null)) {
      return res.status(400).json({
        success: false,
        error: 'custom_props must be a plain object',
        code: 'INVALID_CUSTOM_PROPS'
      });
    }

    // Get current task
    const taskResult = await pool.query('SELECT id, status, custom_props FROM tasks WHERE id = $1', [task_id]);
    if (taskResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Task not found',
        code: 'TASK_NOT_FOUND'
      });
    }

    const task = taskResult.rows[0];
    const currentStatus = task.status;

    // Validate status transition if status is being changed
    if (status) {
      const allowedTransitions = {
        'pending': ['in_progress'],
        'queued': ['in_progress'],
        'in_progress': ['completed', 'failed'],
        'completed': [],
        'failed': []
      };

      if (!allowedTransitions[currentStatus]?.includes(status)) {
        return res.status(409).json({
          success: false,
          error: 'Invalid status transition',
          code: 'INVALID_TRANSITION',
          current_status: currentStatus,
          requested_status: status,
          allowed: allowedTransitions[currentStatus] || []
        });
      }
    }

    // Build dynamic UPDATE query
    const setClauses = ['updated_at = NOW()'];
    const params = [];
    let paramIdx = 1;

    if (status) {
      const changedAt = new Date().toISOString();
      const historyEntry = { from: currentStatus, to: status, changed_at: changedAt, source: 'engine' };
      setClauses.push(`status = $${paramIdx++}`);
      params.push(status);
      setClauses.push(`status_history = status_history || $${paramIdx++}::jsonb`);
      params.push(JSON.stringify([historyEntry]));
    }

    if (custom_props) {
      // JSONB merge: existing keys preserved, overlapping keys overwritten with new values
      setClauses.push(`custom_props = COALESCE(custom_props, '{}'::jsonb) || $${paramIdx++}::jsonb`);
      params.push(JSON.stringify(custom_props));
    }

    params.push(task_id);
    const updateResult = await pool.query(
      `UPDATE tasks SET ${setClauses.join(', ')} WHERE id = $${paramIdx} RETURNING status, custom_props, updated_at`,
      params
    );

    const updatedTask = updateResult.rows[0];

    if (status) {
      await emitEvent('task_status_changed', {
        task_id,
        from: currentStatus,
        to: status,
        source: 'engine',
        timestamp: new Date().toISOString()
      });
    }

    if (custom_props) {
      await emitEvent('task_props_updated', {
        task_id,
        custom_props: updatedTask.custom_props,
        source: 'engine',
        timestamp: new Date().toISOString()
      });
    }

    res.json({
      success: true,
      task_id,
      status: updatedTask.status,
      custom_props: updatedTask.custom_props,
      updated_at: updatedTask.updated_at
    });
  } catch (err) {
    console.error('Failed to update task:', err);
    res.status(500).json({
      success: false,
      error: 'Failed to update task',
      code: 'DATABASE_ERROR',
      details: err.message
    });
  }
});


// ==================== Blocked Tasks API ====================

/**
 * GET /api/brain/tasks/blocked
 * 查询当前所有 blocked 任务
 */
router.get('/tasks/blocked', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT id, title, status, task_type, priority,
             blocked_at, blocked_reason, blocked_until,
             updated_at
      FROM tasks
      WHERE status = 'blocked'
      ORDER BY blocked_until ASC NULLS LAST
    `);
    res.json({ success: true, tasks: result.rows, count: result.rows.length });
  } catch (err) {
    res.status(500).json({ error: 'Failed to get blocked tasks', details: err.message });
  }
});

/**
 * POST /api/brain/tasks/:taskId/unblock
 * 手动解除任务阻塞，释放回 queued
 */
router.post('/tasks/:taskId/unblock', async (req, res) => {
  try {
    const { taskId } = req.params;
    const { unblockTask } = await import('./task-updater.js');
    const result = await unblockTask(taskId);
    if (!result.success) {
      return res.status(400).json({ error: result.error });
    }
    res.json({ success: true, task: result.task });
  } catch (err) {
    res.status(500).json({ error: 'Failed to unblock task', details: err.message });
  }
});

// ==================== Quarantine API ====================

/**
 * GET /api/brain/quarantine
 * 获取隔离区中的任务列表
 */
router.get('/quarantine', async (req, res) => {
  try {
    const tasks = await getQuarantinedTasks();
    const stats = await getQuarantineStats();
    res.json({
      success: true,
      stats,
      tasks,
      reasons: QUARANTINE_REASONS,
      actions: REVIEW_ACTIONS
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to get quarantine', details: err.message });
  }
});

/**
 * GET /api/brain/quarantine/stats
 * 获取隔离区统计
 */
router.get('/quarantine/stats', async (req, res) => {
  try {
    const stats = await getQuarantineStats();
    res.json({ success: true, ...stats });
  } catch (err) {
    res.status(500).json({ error: 'Failed to get stats', details: err.message });
  }
});

/**
 * POST /api/brain/quarantine/:taskId/release
 * 释放任务从隔离区
 * Body: { action: "release"|"retry_once"|"cancel"|"modify", reason?: string, new_prd?: string }
 */
router.post('/quarantine/:taskId/release', async (req, res) => {
  try {
    const { taskId } = req.params;
    const { action, reason, new_prd, reviewer } = req.body;

    if (!action || !REVIEW_ACTIONS[action.toUpperCase()]) {
      return res.status(400).json({
        error: 'Invalid action',
        valid_actions: Object.keys(REVIEW_ACTIONS)
      });
    }

    const result = await releaseTask(taskId, action, {
      reason,
      new_prd,
      reviewer: reviewer || 'api'
    });

    res.json(result);
  } catch (err) {
    res.status(500).json({ error: 'Failed to release task', details: err.message });
  }
});

/**
 * POST /api/brain/quarantine/:taskId
 * 手动隔离任务
 * Body: { reason?: string, details?: object }
 */
router.post('/quarantine/:taskId', async (req, res) => {
  try {
    const { taskId } = req.params;
    const { reason, details } = req.body;

    const result = await quarantineTask(
      taskId,
      reason || QUARANTINE_REASONS.MANUAL,
      details || { manual: true, reviewer: 'api' }
    );

    res.json(result);
  } catch (err) {
    res.status(500).json({ error: 'Failed to quarantine task', details: err.message });
  }
});

/**
 * POST /api/brain/quarantine/release-all
 * 批量释放所有隔离任务（谨慎使用）
 * Body: { action: "release"|"cancel", confirm: true }
 */
router.post('/quarantine/release-all', async (req, res) => {
  try {
    const { action, confirm } = req.body;

    if (!confirm) {
      return res.status(400).json({ error: 'Must set confirm: true to release all' });
    }

    if (!action || !['release', 'cancel'].includes(action)) {
      return res.status(400).json({ error: 'action must be "release" or "cancel"' });
    }

    const tasks = await getQuarantinedTasks();
    const results = [];

    for (const task of tasks) {
      const result = await releaseTask(task.id, action, { reviewer: 'batch-api' });
      results.push({ task_id: task.id, ...result });
    }

    res.json({
      success: true,
      action,
      processed: results.length,
      results
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to release all', details: err.message });
  }
});


// ==================== Task Routing API ====================

/**
 * GET /api/brain/task-types
 * Get available task types and their agent mappings
 */
router.get('/task-types', (req, res) => {
  res.json({
    success: true,
    task_types: TASK_TYPE_AGENT_MAP,
    description: {
      dev: '开发任务 - 交给 Caramel (/dev)',
      talk: '对话任务 - HK MiniMax',
      qa: 'QA 任务 - 交给 小检 (/qa)',
      audit: '审计任务 - 交给 小审 (/audit)',
      research: '调研任务 - 需要人工或 Opus 处理'
    }
  });
});

/**
 * POST /api/brain/route-task
 * Get agent routing for a task
 */
router.post('/route-task', async (req, res) => {
  try {
    const { task_id, task_type } = req.body;

    let task;
    if (task_id) {
      const result = await pool.query('SELECT * FROM tasks WHERE id = $1', [task_id]);
      if (result.rows.length === 0) {
        return res.status(404).json({ success: false, error: 'Task not found' });
      }
      task = result.rows[0];
    } else if (task_type) {
      task = { task_type };
    } else {
      return res.status(400).json({ success: false, error: 'task_id or task_type is required' });
    }

    const agent = routeTask(task);

    res.json({
      success: true,
      task_type: task.task_type || 'dev',
      agent,
      requires_manual: agent === null
    });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to route task', details: err.message });
  }
});

// ==================== Task Router API ====================

/**
 * POST /api/brain/identify-work-type
 * Identify if input is a single task or initiative
 */
router.post('/identify-work-type', (req, res) => {
  try {
    const { input } = req.body;

    if (!input) {
      return res.status(400).json({ success: false, error: 'input is required' });
    }

    const workType = identifyWorkType(input);
    res.json({ success: true, input, work_type: workType });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to identify work type', details: err.message });
  }
});

/**
 * GET /api/brain/task-locations
 * Get location mapping for all task types
 */
router.get('/task-locations', (req, res) => {
  res.json({
    success: true,
    locations: LOCATION_MAP,
    valid_task_types: getValidTaskTypes(),
    description: {
      us: '美国 VPS - Claude (开发、审查)',
      hk: '香港 VPS - MiniMax (自动化、数据处理)'
    }
  });
});

/**
 * POST /api/brain/route-task-create
 * Get routing decision for creating a task
 */
router.post('/route-task-create', (req, res) => {
  try {
    const { title, task_type, initiative_id, feature_id, is_recurring } = req.body;

    if (!title && !task_type) {
      return res.status(400).json({ success: false, error: 'title or task_type is required' });
    }

    const routing = routeTaskCreate({ title, task_type, feature_id: initiative_id || feature_id, is_recurring });
    res.json({ success: true, ...routing });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to route task create', details: err.message });
  }
});

/**
 * GET /api/brain/task-router/diagnose/:kr_id
 * Diagnose task dispatch status for a specific KR
 *
 * Returns a detailed diagnosis:
 * - KR info (title, status, priority, progress)
 * - All Projects → Initiatives → Tasks hierarchy
 * - Dispatch blockers (reasons why tasks are not being queued/dispatched)
 * - Per-initiative task counts and recent task list with routing info
 */
router.get('/task-router/diagnose/:kr_id', async (req, res) => {
  try {
    const { kr_id } = req.params;

    if (!kr_id) {
      return res.status(400).json({ success: false, error: 'kr_id is required' });
    }

    const diagnosis = await diagnoseKR(kr_id, pool);

    if (!diagnosis) {
      return res.status(404).json({ success: false, error: `KR not found: ${kr_id}` });
    }

    res.json({ success: true, ...diagnosis });
  } catch (err) {
    console.error(`[task-router/diagnose] error: ${err.message}`);
    res.status(500).json({ success: false, error: 'Failed to diagnose KR', details: err.message });
  }
});

// ==================== Reflections API ====================

/**
 * GET /api/brain/reflections
 * Get reflections (issues, learnings, improvements)
 */
router.get('/reflections', async (req, res) => {
  try {
    const { type, project_id, limit = 50 } = req.query;

    let query = `
      SELECT r.*, p.name as project_name
      FROM reflections r
      LEFT JOIN projects p ON r.project_id = p.id
      WHERE 1=1
    `;
    const params = [];
    let paramIndex = 1;

    if (type) {
      query += ` AND r.type = $${paramIndex++}`;
      params.push(type);
    }

    if (project_id) {
      query += ` AND r.project_id = $${paramIndex++}`;
      params.push(project_id);
    }

    query += ` ORDER BY r.created_at DESC LIMIT $${paramIndex}`;
    params.push(parseInt(limit));

    const result = await pool.query(query, params);
    res.json({ success: true, reflections: result.rows });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to get reflections', details: err.message });
  }
});

/**
 * POST /api/brain/reflections
 * Create a new reflection
 */
router.post('/reflections', async (req, res) => {
  try {
    const { type, title, content, project_id, source_task_id, source_goal_id, tags } = req.body;

    if (!type || !title) {
      return res.status(400).json({ success: false, error: 'type and title are required' });
    }

    const validTypes = ['issue', 'learning', 'improvement'];
    if (!validTypes.includes(type)) {
      return res.status(400).json({ success: false, error: `type must be one of: ${validTypes.join(', ')}` });
    }

    const result = await pool.query(`
      INSERT INTO reflections (type, title, content, project_id, source_task_id, source_goal_id, tags)
      VALUES ($1, $2, $3, $4, $5, $6, $7)
      RETURNING *
    `, [type, title, content, project_id, source_task_id, source_goal_id, tags]);

    res.json({ success: true, reflection: result.rows[0] });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to create reflection', details: err.message });
  }
});

// ==================== Execution Logs API ====================

/**
 * GET /tasks/:taskId/logs
 * 获取任务执行日志
 */
router.get('/tasks/:taskId/logs', async (req, res) => {
  try {
    const { taskId } = req.params;
    const { offset = 0, limit = 1000 } = req.query;

    // 1. Get task metadata to find log file path
    const taskResult = await pool.query(
      'SELECT id, title, metadata FROM tasks WHERE id = $1',
      [taskId]
    );

    if (taskResult.rows.length === 0) {
      return res.status(404).json({ error: 'Task not found' });
    }

    const task = taskResult.rows[0];
    const metadata = task.metadata || {};
    const logFile = metadata.log_file;

    if (!logFile) {
      return res.json({
        task_id: taskId,
        task_title: task.title,
        logs: [],
        message: 'No log file associated with this task'
      });
    }

    // 2. Read log file
    const fs = await import('fs/promises');
    const path = await import('path');

    try {
      const logContent = await fs.readFile(logFile, 'utf-8');
      const lines = logContent.split('\n');

      // Apply pagination
      const start = parseInt(offset);
      const end = start + parseInt(limit);
      const paginatedLines = lines.slice(start, end);

      res.json({
        task_id: taskId,
        task_title: task.title,
        log_file: logFile,
        total_lines: lines.length,
        offset: start,
        limit: parseInt(limit),
        logs: paginatedLines
      });
    } catch (fileErr) {
      if (fileErr.code === 'ENOENT') {
        return res.json({
          task_id: taskId,
          task_title: task.title,
          log_file: logFile,
          logs: [],
          message: 'Log file not found on disk'
        });
      }
      throw fileErr;
    }
  } catch (err) {
    res.status(500).json({ error: 'Failed to get task logs', details: err.message });
  }
});

/**
 * GET /tasks/:taskId/checkpoints
 * 获取任务的 checkpoint 信息
 */
router.get('/tasks/:taskId/checkpoints', async (req, res) => {
  try {
    const { taskId } = req.params;

    // Get task with metadata
    const taskResult = await pool.query(
      'SELECT id, title, status, metadata, created_at, started_at, completed_at FROM tasks WHERE id = $1',
      [taskId]
    );

    if (taskResult.rows.length === 0) {
      return res.status(404).json({ error: 'Task not found' });
    }

    const task = taskResult.rows[0];
    const metadata = task.metadata || {};

    // Extract checkpoint-related information
    const checkpoints = [];

    // Add task lifecycle checkpoints
    if (task.created_at) {
      checkpoints.push({
        timestamp: task.created_at,
        event: 'task_created',
        status: 'queued'
      });
    }

    if (task.started_at) {
      checkpoints.push({
        timestamp: task.started_at,
        event: 'task_started',
        status: 'running'
      });
    }

    if (task.completed_at) {
      checkpoints.push({
        timestamp: task.completed_at,
        event: 'task_completed',
        status: task.status
      });
    }

    // Add any additional checkpoints from metadata
    if (metadata.checkpoints && Array.isArray(metadata.checkpoints)) {
      checkpoints.push(...metadata.checkpoints);
    }

    // Sort by timestamp
    checkpoints.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

    res.json({
      task_id: taskId,
      task_title: task.title,
      current_status: task.status,
      checkpoints
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to get task checkpoints', details: err.message });
  }
});


/**
 * GET /api/brain/tasks/:id/ci-diagnosis
 * 返回任务最近一次 CI 失败的自动诊断结果
 */
router.get('/tasks/:id/ci-diagnosis', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `SELECT metadata->>'ci_diagnosis' AS ci_diagnosis FROM tasks WHERE id = $1`,
      [id]
    );
    if (!result.rows.length) {
      return res.status(404).json({ error: 'task not found' });
    }
    const raw = result.rows[0].ci_diagnosis;
    if (!raw) {
      return res.status(404).json({ error: 'no CI diagnosis available for this task' });
    }
    return res.json(JSON.parse(raw));
  } catch (err) {
    console.error('[GET /tasks/:id/ci-diagnosis] error:', err.message);
    return res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/brain/tasks/:id/block
 * 手动阻塞任务（临时暂停调度，等待条件就绪后自动或手动恢复）
 * 请求体：{ reason, detail, until }
 */
router.post('/tasks/:id/block', async (req, res) => {
  try {
    const { id } = req.params;
    const { reason = 'manual', detail = null, until = null } = req.body || {};

    const { blockTask } = await import('./task-updater.js');
    const result = await blockTask(id, { reason, detail, until: until ? new Date(until) : null });

    if (!result.success) {
      return res.status(404).json({ error: result.error });
    }

    res.json({
      success: true,
      task_id: id,
      status: 'blocked',
      reason,
      blocked_until: result.task?.blocked_until || null,
    });
  } catch (err) {
    console.error('[API] tasks/:id/block error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/brain/tasks/:id/unblock
 * 手动解除任务阻塞，状态回 queued
 */
router.post('/tasks/:id/unblock', async (req, res) => {
  try {
    const { id } = req.params;

    const { unblockTask } = await import('./task-updater.js');
    const result = await unblockTask(id);

    if (!result.success) {
      return res.status(404).json({ error: result.error });
    }

    res.json({
      success: true,
      task_id: id,
      status: 'queued',
    });
  } catch (err) {
    console.error('[API] tasks/:id/unblock error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/brain/tasks/:id/dispatch
 * 手动派发单个任务（用户从前端点击"派发"按钮）
 * 跳过自动调度的 drain/billing/slot 检查，但保留执行器可用性检查
 */
router.post('/tasks/:id/dispatch', async (req, res) => {
  try {
    const { id } = req.params;

    // 1. 查找任务
    const taskResult = await pool.query('SELECT * FROM tasks WHERE id = $1', [id]);
    if (taskResult.rows.length === 0) {
      return res.status(404).json({ error: 'task not found' });
    }

    const task = taskResult.rows[0];

    // 2. 只允许 queued 状态的任务被派发
    if (task.status !== 'queued') {
      return res.status(409).json({
        error: `task status is '${task.status}', only 'queued' tasks can be dispatched`,
        current_status: task.status
      });
    }

    // 3. 更新为 in_progress
    await pool.query(
      `UPDATE tasks SET status = 'in_progress', updated_at = NOW(),
       metadata = COALESCE(metadata, '{}'::jsonb) || '{"manually_dispatched": true}'::jsonb
       WHERE id = $1`,
      [id]
    );

    // 4. 检查执行器可用性
    const ceceliaAvailable = await checkCeceliaRunAvailable();
    if (!ceceliaAvailable.available) {
      await pool.query(`UPDATE tasks SET status = 'queued', updated_at = NOW() WHERE id = $1`, [id]);
      return res.status(503).json({
        error: 'executor not available',
        detail: ceceliaAvailable.error
      });
    }

    // 5. 触发执行
    const execResult = await triggerCeceliaRun(task);
    if (!execResult.success) {
      await pool.query(`UPDATE tasks SET status = 'queued', updated_at = NOW() WHERE id = $1`, [id]);
      return res.status(500).json({
        error: 'dispatch failed',
        detail: execResult.error || execResult.reason
      });
    }

    res.json({
      success: true,
      task_id: id,
      title: task.title,
      run_id: execResult.runId
    });
  } catch (err) {
    console.error('[API] tasks/:id/dispatch error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/brain/tasks/:id/request-intent-expand
 * 根据父任务创建 intent_expand 子任务
 * 沿 task.project_id → projects.kr_id → goals(KR).parent_id → goals(OKR).parent_id → goals(Vision)
 * 链路查询战略上下文，作为 intent_expand 子任务的 prompt 一部分
 */
router.post('/tasks/:id/request-intent-expand', async (req, res) => {
  try {
    const { id: parentId } = req.params;

    // 1. 查找父任务
    const parentResult = await pool.query('SELECT * FROM tasks WHERE id = $1', [parentId]);
    if (parentResult.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'parent task not found' });
    }
    const parentTask = parentResult.rows[0];

    // 2. 沿 project_id → KR → OKR → Vision 链查询上下文
    let context = { project: null, kr: null, okr: null, vision: null };

    if (parentTask.project_id) {
      const projectResult = await pool.query(
        'SELECT id, name, kr_id FROM projects WHERE id = $1',
        [parentTask.project_id]
      );
      if (projectResult.rows.length > 0) {
        const project = projectResult.rows[0];
        context.project = { id: project.id, name: project.name };

        if (project.kr_id) {
          // 查 KR（goals 表 type='area_kr' 或 'global_kr'）
          const krResult = await pool.query(
            'SELECT id, title, description, parent_id FROM goals WHERE id = $1',
            [project.kr_id]
          );
          if (krResult.rows.length > 0) {
            const kr = krResult.rows[0];
            context.kr = { id: kr.id, title: kr.title, description: kr.description };

            if (kr.parent_id) {
              // 查 OKR
              const okrResult = await pool.query(
                'SELECT id, title, description, parent_id FROM goals WHERE id = $1',
                [kr.parent_id]
              );
              if (okrResult.rows.length > 0) {
                const okr = okrResult.rows[0];
                context.okr = { id: okr.id, title: okr.title, description: okr.description };

                if (okr.parent_id) {
                  // 查 Vision/Mission
                  const visionResult = await pool.query(
                    'SELECT id, title, description FROM goals WHERE id = $1',
                    [okr.parent_id]
                  );
                  if (visionResult.rows.length > 0) {
                    const vision = visionResult.rows[0];
                    context.vision = { id: vision.id, title: vision.title, description: vision.description };
                  }
                }
              }
            }
          }
        } else {
          // 尝试通过 project_kr_links 查 kr_id
          const krLinkResult = await pool.query(
            'SELECT kr_id FROM project_kr_links WHERE project_id = $1 LIMIT 1',
            [parentTask.project_id]
          );
          if (krLinkResult.rows.length > 0) {
            const krId = krLinkResult.rows[0].kr_id;
            const krResult = await pool.query(
              'SELECT id, title, description, parent_id FROM goals WHERE id = $1',
              [krId]
            );
            if (krResult.rows.length > 0) {
              const kr = krResult.rows[0];
              context.kr = { id: kr.id, title: kr.title, description: kr.description };
            }
          }
        }
      }
    }

    // 3. 构建子任务描述（包含战略上下文）
    const contextSummary = [
      context.vision ? `**Vision/Mission**: ${context.vision.title}` : null,
      context.okr ? `**OKR**: ${context.okr.title}` : null,
      context.kr ? `**KR**: ${context.kr.title}` : null,
      context.project ? `**Project**: ${context.project.name}` : null,
    ].filter(Boolean).join('\n');

    const description = [
      `## 意图扩展任务`,
      `父任务 ID: ${parentId}`,
      `父任务标题: ${parentTask.title}`,
      '',
      `## 战略上下文`,
      contextSummary || '（未找到关联的 OKR/KR 链路，请根据任务描述判断）',
      '',
      `## 父任务 PRD`,
      parentTask.prd_content || parentTask.description || '（无 PRD 内容）',
      '',
      `## 任务指令`,
      '请根据以上战略上下文，补全并丰富父任务的 PRD，确保实现方向与 OKR/Vision 对齐。',
      '补全后的 enriched PRD 通过 execution-callback 写入父任务 metadata.enriched_prd。',
    ].join('\n');

    // 4. 创建 intent_expand 子任务
    const { createTask } = await import('../actions.js');
    const subTaskResult = await createTask({
      title: `[意图扩展] ${parentTask.title}`,
      description,
      priority: parentTask.priority || 'P1',
      goal_id: parentTask.goal_id,
      project_id: parentTask.project_id,
      task_type: 'intent_expand',
      trigger_source: 'brain_auto',
      domain: parentTask.domain || 'agent_ops',
      payload: {
        parent_task_id: parentId,
        context_chain: context,
      },
    });

    if (!subTaskResult.success) {
      return res.status(500).json({ success: false, error: 'failed to create intent_expand task' });
    }

    return res.json({
      success: true,
      task_id: subTaskResult.task.id,
      parent_task_id: parentId,
      context_found: {
        has_project: !!context.project,
        has_kr: !!context.kr,
        has_okr: !!context.okr,
        has_vision: !!context.vision,
      },
      deduplicated: subTaskResult.deduplicated || false,
    });
  } catch (err) {
    console.error('[API] tasks/:id/request-intent-expand error:', err.message);
    return res.status(500).json({ success: false, error: err.message });
  }
});

export default router;
