import { afterEach,expect,it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { versionsDatabase } from '../../../__tests__/fixtures/definition-versions-db.js';
import { companyKrSpec,registerCompanyKrWorkflow } from '../../company-kr-registration.js';
import {migrationTable} from '../../../__tests__/fixtures/minimum-definition-schema.js';
let fixture;afterEach(async()=>{await fixture?.close();fixture=null;});
it('公司KR正式adapter固定同repo源码、完整codefile绑定与UUID，不接执行任务或改运行历史',async()=>{
  fixture=await versionsDatabase();await fixture.migrate();const {db}=fixture,s=companyKrSpec,vs=randomUUID();
  await db.query(migrationTable('433_ops_projection.sql','ops_agents'));
  await db.query('INSERT INTO areas(id,name) VALUES($1,$2)',[s.area_id,'公司']);
  await db.query('WITH vs AS (INSERT INTO value_streams(id,name,parent_journey_id,capability_code) VALUES($1,$2,NULL,NULL)) INSERT INTO capabilities(id,name,parent_journey_id,capability_code) VALUES($3,$4,$1,$5)',[vs,'管家',s.capability_id,s.capability_name,s.capability_code]);
  await db.query("INSERT INTO ops_agents(source,host_alias,name) VALUES('openclaw','mmv',$1)",[s.agent]);
  await db.query("INSERT INTO ops_workflows(source,wf_id,name) VALUES('scheduler',$1,'公司KR')",[s.runtime]);
  const result=await registerCompanyKrWorkflow(db,{revision:'a'.repeat(40),spec:s,readSource:async()=>JSON.stringify(s),readBinding:async()=> 'export const code=true;\n',definitionsOnly:true});
  const workflow=(await db.query('SELECT * FROM workflows WHERE id=$1',[result.workflow_id])).rows[0];
  expect(workflow).toMatchObject({source_repo:'perfectuser21/cecelia',source_path:'packages/brain/config/company-kr-workflow.json'});
  const versions=(await db.query('SELECT * FROM activity_definition_versions')).rows;
  expect(versions).toHaveLength(5);
  expect(versions.every(a=>a.payload.implementation_bindings.length&&a.payload.implementation_bindings.every(b=>b.status==='verified'&&b.kind==='code'))).toBe(true);
  expect(versions.every(a=>a.payload.steps.every(s=>typeof s.step_id==='string'))).toBe(true);
  expect((await db.query('SELECT count(*)::int n FROM tasks')).rows[0].n).toBe(0);
  expect((await db.query('SELECT count(*)::int n FROM task_runs')).rows[0].n).toBe(0);
});
