"""State management module for Cecelia Semantic Brain."""

from .focus import (
    select_daily_focus,
    get_daily_focus,
    set_daily_focus,
    clear_daily_focus,
    get_focus_summary,
    FOCUS_OVERRIDE_KEY,
)

from .tick import (
    get_tick_status,
    enable_tick,
    disable_tick,
    execute_tick,
    is_stale,
    TICK_INTERVAL_MINUTES,
    STALE_THRESHOLD_HOURS,
)

from .actions import (
    create_task,
    update_task,
    create_goal,
    update_goal,
    set_memory,
    log_decision,
    batch_update_tasks,
    execute_action,
    ACTION_HANDLERS,
)

from .goals import (
    list_objectives,
    list_key_results,
    get_goal,
    get_objective_with_tasks,
    delete_goal,
    update_objective_progress,
    get_goals_summary,
)

from .queue import (
    get_queue,
    init_queue,
    get_next_prd,
    start_current_prd,
    complete_prd,
    fail_prd,
    retry_failed,
    clear_queue,
    get_queue_summary,
    PRD_QUEUE_KEY,
)

from .patrol import (
    get_stale_tasks,
    get_task_by_id,
    record_diagnosis,
    record_action,
    get_patrol_logs,
    get_patrol_summary,
    ensure_patrol_table,
    DIAGNOSIS_STUCK_AFTER_SKILL,
    DIAGNOSIS_CI_TIMEOUT,
    DIAGNOSIS_PROCESS_DEAD,
    DIAGNOSIS_NORMAL,
    DIAGNOSIS_NEEDS_HUMAN,
    ACTION_RESTART,
    ACTION_CONTINUE,
    ACTION_MARK_HUMAN,
    ACTION_NONE,
    RESULT_SUCCESS,
    RESULT_FAILED,
    RESULT_SKIPPED,
    STALE_THRESHOLD_MINUTES,
    CI_TIMEOUT_MINUTES,
)

__all__ = [
    # Focus
    "select_daily_focus",
    "get_daily_focus",
    "set_daily_focus",
    "clear_daily_focus",
    "get_focus_summary",
    "FOCUS_OVERRIDE_KEY",
    # Tick
    "get_tick_status",
    "enable_tick",
    "disable_tick",
    "execute_tick",
    "is_stale",
    "TICK_INTERVAL_MINUTES",
    "STALE_THRESHOLD_HOURS",
    # Actions
    "create_task",
    "update_task",
    "create_goal",
    "update_goal",
    "set_memory",
    "log_decision",
    "batch_update_tasks",
    "execute_action",
    "ACTION_HANDLERS",
    # Goals
    "list_objectives",
    "list_key_results",
    "get_goal",
    "get_objective_with_tasks",
    "delete_goal",
    "update_objective_progress",
    "get_goals_summary",
    # Queue
    "get_queue",
    "init_queue",
    "get_next_prd",
    "start_current_prd",
    "complete_prd",
    "fail_prd",
    "retry_failed",
    "clear_queue",
    "get_queue_summary",
    "PRD_QUEUE_KEY",
    # Patrol
    "get_stale_tasks",
    "get_task_by_id",
    "record_diagnosis",
    "record_action",
    "get_patrol_logs",
    "get_patrol_summary",
    "ensure_patrol_table",
    "DIAGNOSIS_STUCK_AFTER_SKILL",
    "DIAGNOSIS_CI_TIMEOUT",
    "DIAGNOSIS_PROCESS_DEAD",
    "DIAGNOSIS_NORMAL",
    "DIAGNOSIS_NEEDS_HUMAN",
    "ACTION_RESTART",
    "ACTION_CONTINUE",
    "ACTION_MARK_HUMAN",
    "ACTION_NONE",
    "RESULT_SUCCESS",
    "RESULT_FAILED",
    "RESULT_SKIPPED",
    "STALE_THRESHOLD_MINUTES",
    "CI_TIMEOUT_MINUTES",
]
