"""State Layer - Intelligence service state management.

Note: Brain state (focus, tick, goals, queue, actions) has been migrated to Node.js Brain.
This module only exports patrol and agent_monitor functionality.
"""

from .patrol import (
    get_stale_tasks,
    get_task_by_id,
    record_diagnosis,
    record_action,
    get_patrol_logs,
    get_patrol_summary,
    ensure_patrol_table,
    DIAGNOSIS_STUCK_AFTER_SKILL,
    DIAGNOSIS_CI_TIMEOUT,
    DIAGNOSIS_PROCESS_DEAD,
    DIAGNOSIS_NORMAL,
    DIAGNOSIS_NEEDS_HUMAN,
    ACTION_RESTART,
    ACTION_CONTINUE,
    ACTION_MARK_HUMAN,
    ACTION_NONE,
    RESULT_SUCCESS,
    RESULT_FAILED,
    RESULT_SKIPPED,
    STALE_THRESHOLD_MINUTES,
    CI_TIMEOUT_MINUTES,
)

from .agent_monitor import (
    ensure_agent_tables,
    parse_output_line,
    create_or_update_run,
    record_event,
    update_run_from_event,
    get_runs,
    get_run,
    get_run_by_agent_id,
    get_events,
    complete_run,
    get_active_runs,
    get_runs_summary,
    EVENT_USER_MESSAGE,
    EVENT_TOOL_USE,
    EVENT_TOOL_RESULT,
    EVENT_TEXT,
    EVENT_HOOK_PROGRESS,
    STATUS_RUNNING,
    STATUS_COMPLETED,
    STATUS_FAILED,
    STATUS_STALE,
)

__all__ = [
    # Patrol
    "get_stale_tasks",
    "get_task_by_id",
    "record_diagnosis",
    "record_action",
    "get_patrol_logs",
    "get_patrol_summary",
    "ensure_patrol_table",
    "DIAGNOSIS_STUCK_AFTER_SKILL",
    "DIAGNOSIS_CI_TIMEOUT",
    "DIAGNOSIS_PROCESS_DEAD",
    "DIAGNOSIS_NORMAL",
    "DIAGNOSIS_NEEDS_HUMAN",
    "ACTION_RESTART",
    "ACTION_CONTINUE",
    "ACTION_MARK_HUMAN",
    "ACTION_NONE",
    "RESULT_SUCCESS",
    "RESULT_FAILED",
    "RESULT_SKIPPED",
    "STALE_THRESHOLD_MINUTES",
    "CI_TIMEOUT_MINUTES",
    # Agent Monitor
    "ensure_agent_tables",
    "parse_output_line",
    "create_or_update_run",
    "record_event",
    "update_run_from_event",
    "get_runs",
    "get_run",
    "get_run_by_agent_id",
    "get_events",
    "complete_run",
    "get_active_runs",
    "get_runs_summary",
    "EVENT_USER_MESSAGE",
    "EVENT_TOOL_USE",
    "EVENT_TOOL_RESULT",
    "EVENT_TEXT",
    "EVENT_HOOK_PROGRESS",
    "STATUS_RUNNING",
    "STATUS_COMPLETED",
    "STATUS_FAILED",
    "STATUS_STALE",
]
