#!/usr/bin/env bash
# install-launchers.sh — 幂等安装 codex/grok launcher aliases
#
# 向 ~/.zshrc 追加受控 alias block（cecelia-launchers-begin/end）。
# 重复运行不产生重复内容（INV-9）。
# 不覆盖 ~/.zshrc 已有内容。
#
# 使用方式：bash scripts/install-launchers.sh

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZSHRC="${HOME}/.zshrc"

# 确保 ~/.zshrc 存在
touch "$ZSHRC"

# 受控 block 标记
BEGIN_MARKER="# cecelia-launchers-begin"
END_MARKER="# cecelia-launchers-end"

# 检查是否已经安装（幂等：block 已存在则跳过）
if grep -qF "$BEGIN_MARKER" "$ZSHRC" 2>/dev/null; then
  echo "[install-launchers] alias block already present in ${ZSHRC} — skip"
  exit 0
fi

# 追加受控 block
cat >> "$ZSHRC" << BLOCK

${BEGIN_MARKER}
# Cecelia headless launcher aliases — auto-generated by install-launchers.sh
alias codex-launch='bash ${SCRIPT_DIR}/codex-launch.sh'
alias grok-launch='bash ${SCRIPT_DIR}/grok-launch.sh'
${END_MARKER}
BLOCK

echo "[install-launchers] aliases installed in ${ZSHRC}"
echo "  codex-launch → ${SCRIPT_DIR}/codex-launch.sh"
echo "  grok-launch  → ${SCRIPT_DIR}/grok-launch.sh"
echo ""
echo "Run 'source ${ZSHRC}' or open a new terminal to activate."
