import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {DB_DEFAULTS} from '../db-config.js';
import {createPhoneScheduleSchema,applyPhoneScheduleMigration} from '../__tests__/fixtures/phone-schedule-schema.js';
import {importLegacyPolicy} from '../execution-directory/store.js';
import {LEGACY_BINDINGS} from '../execution-directory/legacy-policy.js';
import {PHONE_SCHEDULE_REGISTRY_AUTHORITY} from './task-authority.js';
const holder=vi.hoisted(()=>({pool:null}));
vi.mock('../db.js',()=>({default:{query:(...a)=>holder.pool.query(...a),connect:(...a)=>holder.pool.connect(...a)}}));
vi.mock('../task-updater.js',()=>({broadcastTaskState:vi.fn()}));
const schema=`phone_schedule_${process.pid}_${randomUUID().replaceAll('-','')}`;
if(DB_DEFAULTS.database!=='cecelia_scratch'&&!(process.env.CI==='true'&&/_(test)$/.test(DB_DEFAULTS.database)))throw Error('phone_schedule_fixture_scratch_required');
const admin=new pg.Client(DB_DEFAULTS);
let pool,store,legacyBefore,legacyAfter;
const phone={machine_id:'xian-mac-m1',serial:`fixture-${process.pid}`,host:'xian-m1',profile:'fixture-profile',account_id:'fixture-account',action:'adb_get_state'};
const auth={registryAuthority:PHONE_SCHEDULE_REGISTRY_AUTHORITY};
const now=new Date();now.setSeconds(10,0);const due=new Date(now);due.setSeconds(0,0);
beforeAll(async()=>{
 await admin.connect();await admin.query(`CREATE SCHEMA ${schema}`);
 pool=new pg.Pool({...DB_DEFAULTS,max:8,options:`-c search_path=${schema}`});holder.pool=pool;
 const location=(await pool.query('SELECT current_database() database,current_schema() schema')).rows[0];expect(location).toEqual({database:DB_DEFAULTS.database,schema});process.stdout.write(`phone_schedule_fixture_location ${JSON.stringify(location)}\n`);
 await createPhoneScheduleSchema(pool);
 for(const [,id,name]of LEGACY_BINDINGS)await pool.query("INSERT INTO system_registry(id,type,name,status) VALUES($1,'machine',$2,'active') ON CONFLICT(id) DO NOTHING",[id,`C7 fixture ${name}`]);
 await importLegacyPolicy({pool,env:{FLEET_WORKER_XIAN_MAC_M1_URL:'http://fixture-m1:5231'}});
 await pool.query("INSERT INTO phone_registry(serial,nickname,host,profile,douyin_accounts,enabled) VALUES($1,'C7 fixture',$2,$3,$4,true)",[phone.serial,phone.host,phone.profile,JSON.stringify([{id:phone.account_id,current:true}])]);
 await seedOldLease();await applyPhoneScheduleMigration(pool,'517_phone_scheduled_slots');legacyAfter=await captureLegacy();
 store=await import('./schedule-store.js');
},180000);
afterAll(async()=>{if(pool)await pool.end();await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();},30000);
async function captureLegacy(){return {dispatch:(await pool.query('SELECT * FROM phone_dispatches WHERE serial=$1',[phone.serial])).rows[0],task:(await pool.query('SELECT * FROM tasks WHERE id=(SELECT task_id FROM phone_dispatches WHERE serial=$1)',[phone.serial])).rows[0],grants:(await pool.query('SELECT * FROM execution_grants ORDER BY id')).rows};}
async function seedOldLease(){
 const old=(await pool.query('SELECT v.* FROM execution_nodes n JOIN execution_node_versions v ON v.id=n.current_version_id WHERE n.canonical_id=$1',[phone.machine_id])).rows[0];const version=randomUUID(),grant=randomUUID(),task=randomUUID(),dispatch=randomUUID(),reservation=randomUUID(),execution=randomUUID();
 await pool.query("INSERT INTO execution_node_versions(id,machine_registry_id,revision,identity_mode,worker_id,platform,endpoints,profile,config_hash,state) VALUES($1,$2,2,'legacy-v1','fixture-worker','darwin',$3,$4,$5,'active')",[version,old.machine_registry_id,{phone_ssh:{host:phone.host,port:22,user:'administrator',hub:{host:'mmv',port:22,user:'administrator'}}},old.profile,old.config_hash]);await pool.query('UPDATE execution_nodes SET current_version_id=$1 WHERE canonical_id=$2',[version,phone.machine_id]);
 await pool.query("INSERT INTO execution_grants(id,node_version_id,surface,provider,account_id,profile_id,provenance,state) VALUES($1,$2,'phone_ssh','adb',$3,'adb_get_state','isolated_c7_historical_fixture','active')",[grant,version,phone.account_id]);
 const c=await pool.connect();try{await c.query('BEGIN');await c.query("INSERT INTO tasks(id,title,status,task_type,executor_kind,kind) VALUES($1,'C7 old leased fixture','queued','device_job','phone-ssh-controller','agent')",[task]);
 await c.query("INSERT INTO capacity_reservations(id,machine_id,owner_kind,owner_key,task_id,config_digest,allocation_mode,policy_version,snapshot_time,snapshot_digest,intent_id,worker_id,worker_boot_id,execution_version_id,execution_grant_id) VALUES($1,$2,'phone',$3,$4,$5,'exclusive_unclassified','fixture',now(),$5,$6,'fixture-worker','fixture-boot',$7,$8)",[reservation,phone.machine_id,`phone-${dispatch}`,task,'f'.repeat(64),execution,version,grant]);
 await c.query("INSERT INTO phone_dispatches(id,task_id,reservation_id,serial,machine_id,host,profile,account_id,execution_version_id,execution_grant_id,lease_token,execution_id,worker_id,worker_boot_id,config_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'fixture-worker','fixture-boot',$13)",[dispatch,task,reservation,phone.serial,phone.machine_id,phone.host,phone.profile,phone.account_id,version,grant,randomUUID(),execution,'f'.repeat(64)]);
 await c.query("UPDATE tasks SET status='in_progress',payload=COALESCE(payload,'{}'::jsonb)||jsonb_build_object('phone_dispatch_id',$2::text),claimed_by='phone-fixture' WHERE id=$1",[task,dispatch]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}legacyBefore=await captureLegacy();
}
async function template(){const id=randomUUID();await pool.query("INSERT INTO recurring_tasks(id,title,task_type,cron_expression,recurrence_type,is_active,next_run_at,template) VALUES($1,'C7 fixture','device_job','* * * * *','cron',true,$2,$3)",[id,due,{timezone:'UTC',executor_kind:'phone-ssh-controller',phone_authority:true}]);return id;}
async function register(id,enable=true,sharedPhone=null){const pins=sharedPhone||{...phone,serial:`fixture-${id}`};await pool.query("INSERT INTO phone_registry(serial,nickname,host,profile,douyin_accounts,enabled) VALUES($1,'C7 fixture',$2,$3,$4,true) ON CONFLICT(serial) DO NOTHING",[pins.serial,pins.host,pins.profile,JSON.stringify([{id:pins.account_id,current:true}])]);const r=await store.registerPhoneSchedule(pool,{templateId:id,phone:pins,parentTaskId:null,expiresAt:new Date(Date.now()+120000)},auth);if(enable)await store.setPhoneScheduleState(pool,{registrationId:r.id,revision:Number(r.revision),state:'active'},auth);return r;}
async function run(id){return store.processPhoneScheduledSlot(pool,{templateId:id,now});}
async function totals(id){return (await pool.query(`SELECT (SELECT count(*)::int FROM phone_scheduled_slots WHERE template_id=$1) slots,(SELECT count(*)::int FROM phone_task_owners WHERE template_id=$1) owners,(SELECT count(*)::int FROM tasks WHERE payload->'phone_schedule'->>'template_id'=$1::text) tasks,(SELECT count(*)::int FROM work_routing_receipts WHERE source_id LIKE 'recurring:'||$1::text||':%') receipts`,[id])).rows[0];}
it('517真实迁移独立登记且默认注册为空',async()=>{expect((await pool.query("SELECT version FROM schema_version WHERE version IN ('507','508','509','510','511','512','513','514','515','516','517') ORDER BY version")).rows.map(r=>r.version)).toEqual(['507','508','509','510','511','512','513','514','515','516','517']);expect((await pool.query('SELECT count(*)::int n FROM phone_schedule_registrations')).rows[0].n).toBe(0);});
it('public旗标和伪造authority不能注册；内部初始inactive',async()=>{const id=await template();await expect(run(id)).rejects.toThrow('phone_schedule_unregistered');await expect(store.registerPhoneSchedule(pool,{templateId:id,phone,expiresAt:new Date(Date.now()+60000)},{registryAuthority:true})).rejects.toThrow('phone_schedule_registry_authority_required');expect((await register(id,false)).state).toBe('inactive');await expect(run(id)).rejects.toThrow('phone_schedule_inactive');expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});
it('并发真实连接同slot只有一task/receipt/slot/owner，重复读原task',async()=>{const id=await template();await register(id);const result=await Promise.all([run(id),run(id)]);expect(result.filter(r=>r.state==='created')).toHaveLength(1);expect(await totals(id)).toEqual({slots:1,owners:1,tasks:1,receipts:1});const t=(await pool.query("SELECT * FROM tasks WHERE payload->'phone_schedule'->>'template_id'=$1",[id])).rows[0];expect(t).toMatchObject({task_type:'device_job',executor_kind:'phone-ssh-controller',kind:'agent',status:'queued',created_by:'phone-schedule-service'});expect(t.payload.routing_receipt_id).toBeTruthy();expect((await pool.query('SELECT * FROM work_routing_receipts WHERE id=$1',[t.payload.routing_receipt_id])).rows[0]).toMatchObject({task_id:t.id,source:'scheduler',source_id:`recurring:${id}:${due.toISOString()}`,canonical_task_type:'device_job',work_kind:'operations'});await pool.query('UPDATE recurring_tasks SET next_run_at=$2 WHERE id=$1',[id,due]);expect((await run(id)).state).toBe('existing');expect(await totals(id)).toEqual({slots:1,owners:1,tasks:1,receipts:1});});
it('跨routerversion历史ordinary同source拒绝重绑',async()=>{const id=await template();await register(id);const {createTask}=await import('../actions.js');await pool.query(`CREATE FUNCTION fixture_c7_old_router() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.source_id LIKE 'recurring:${id}:%' THEN NEW.router_version:='fixture-old-version'; END IF;RETURN NEW;END $$;CREATE TRIGGER fixture_c7_old_router BEFORE INSERT ON work_routing_receipts FOR EACH ROW EXECUTE FUNCTION fixture_c7_old_router()`);const old=await createTask({db:pool,source:'scheduler',source_id:`recurring:${id}:${due.toISOString()}`,title:'old ordinary',task_type:'research',allow_unscoped:true,payload:{old:true}});await pool.query('DROP TRIGGER fixture_c7_old_router ON work_routing_receipts;DROP FUNCTION fixture_c7_old_router()');expect((await pool.query('SELECT router_version FROM work_routing_receipts WHERE task_id=$1',[old.task.id])).rows[0].router_version).toBe('fixture-old-version');await expect(run(id)).rejects.toThrow('phone_schedule_route_collision');expect((await pool.query('SELECT executor_kind FROM tasks WHERE id=$1',[old.task.id])).rows[0].executor_kind).toBe(null);expect((await totals(id)).slots).toBe(0);});
async function fault(id,table,column,message){await pool.query(`CREATE FUNCTION fixture_c7_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ${column} THEN RAISE EXCEPTION '${message}'; END IF;RETURN NEW;END $$;CREATE TRIGGER fixture_c7_fault BEFORE ${table==='recurring_tasks'?'UPDATE':'INSERT'} ON ${table} FOR EACH ROW EXECUTE FUNCTION fixture_c7_fault()`);await expect(run(id)).rejects.toThrow(message);expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});expect(new Date((await pool.query('SELECT next_run_at FROM recurring_tasks WHERE id=$1',[id])).rows[0].next_run_at)).toEqual(due);await pool.query(`DROP TRIGGER fixture_c7_fault ON ${table};DROP FUNCTION fixture_c7_fault()`);expect((await run(id)).state).toBe('created');}
it('next_run_at SQL失败全部回滚原slot可重试',async()=>{const id=await template();await register(id);await fault(id,'recurring_tasks',`NEW.id='${id}'::uuid`,'fixture_cas_fault');});
it('真实receipt SQL失败全部回滚原slot可重试',async()=>{const id=await template();await register(id);await fault(id,'work_routing_receipts',`NEW.source_id LIKE 'recurring:${id}:%'`,'fixture_receipt_fault');});
it('queued未dispatch也拒绝旧claim/finish/payload/执行者修改；人类metadata允许',async()=>{const id=await template();await register(id);const {task}=await run(id);for(const sql of ["status='in_progress'","status='completed',result='{}'","claimed_by='old',claimed_at=now()","executor_kind='headed-session'","payload=payload||'{\"evil\":true}'::jsonb"]){await expect(pool.query(`UPDATE tasks SET ${sql} WHERE id=$1`,[task.id])).rejects.toThrow('phone_scheduled_task_managed');}await pool.query("UPDATE tasks SET title='human',priority='P0',due_at=now(),notion_props='{\"human\":true}'::jsonb WHERE id=$1",[task.id]);expect((await pool.query('SELECT title FROM tasks WHERE id=$1',[task.id])).rows[0].title).toBe('human');await expect(pool.query("UPDATE tasks SET title='mixed',result='{}' WHERE id=$1",[task.id])).rejects.toThrow('phone_scheduled_task_managed');});
it('普通task原地变phone拒绝',async()=>{const {createTask}=await import('../actions.js');const r=await createTask({db:pool,title:'ordinary conversion',task_type:'research',allow_unscoped:true});await expect(pool.query("UPDATE tasks SET executor_kind='phone-ssh-controller' WHERE id=$1",[r.task.id])).rejects.toThrow('phone_schedule_insert_required');});
it('仅真实task/receipt无slot/owner的COMMIT被deferred guard拒绝',async()=>{const id=await template();const reg=await register(id);const c=await pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('cecelia.phone_schedule_admission',$1,true)",[`${reg.id}:${reg.revision}:${due.toISOString()}`]);const {createPhoneScheduledTask}=await import('./task-authority.js');await createPhoneScheduledTask({db:c,registration:{...reg,title:'fixture'},slot:due});await expect(c.query('COMMIT')).rejects.toThrow('phone_schedule_owner_required');}finally{await c.query('ROLLBACK');c.release();}expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});
it('pins/revision/owner/slot不能删改',async()=>{const id=await template();const reg=await register(id);const r=await run(id);await expect(pool.query("UPDATE phone_schedule_registrations SET phone=phone||'{\"host\":\"evil\"}' WHERE id=$1",[reg.id])).rejects.toThrow('phone_schedule_registry_managed');await expect(pool.query('DELETE FROM phone_task_owners WHERE task_id=$1',[r.task.id])).rejects.toThrow('phone_schedule_identity_immutable');await expect(pool.query("UPDATE phone_scheduled_slots SET slot=slot+interval '1 minute' WHERE template_id=$1",[id])).rejects.toThrow('phone_schedule_identity_immutable');});
it('模板变化、过期、真实phone pins变化拒建单',async()=>{const id=await template();await register(id);await pool.query("UPDATE recurring_tasks SET template=template||'{\"timezone\":\"Asia/Shanghai\"}' WHERE id=$1",[id]);await expect(run(id)).rejects.toThrow('phone_schedule_template_changed');const id2=await template();const r=await register(id2);await store.setPhoneScheduleState(pool,{registrationId:r.id,revision:Number(r.revision),state:'active',expiresAt:new Date(Date.now()-1)},auth);await expect(run(id2)).rejects.toThrow('phone_schedule_expired');const id3=await template();const reg3=await register(id3);await pool.query('UPDATE phone_registry SET enabled=false WHERE serial=$1',[reg3.phone.serial]);await expect(run(id3)).rejects.toThrow('phone_schedule_phone_changed');await pool.query('UPDATE phone_registry SET enabled=true WHERE serial=$1',[reg3.phone.serial]);});
it('上一slot未知占位不能叠单，不推进next_run_at',async()=>{const id=await template();await register(id);await run(id);const next=new Date(due.getTime()+60000);await pool.query('UPDATE recurring_tasks SET next_run_at=$2 WHERE id=$1',[id,next]);expect((await store.processPhoneScheduledSlot(pool,{templateId:id,now:new Date(next.getTime()+10000)})).state).toBe('overlap');expect((await totals(id)).tasks).toBe(1);expect(new Date((await pool.query('SELECT next_run_at FROM recurring_tasks WHERE id=$1',[id])).rows[0].next_run_at)).toEqual(next);});

it('不同模板同一真实phone未知owner不能叠单',async()=>{const a=await template();const r=await register(a);await run(a);const b=await template();await register(b,true,r.phone);expect((await run(b)).state).toBe('overlap');expect(await totals(b)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});

it('同phone不同模板并发真实连接只能建立一个queued owner',async()=>{const a=await template();const r=await register(a);const b=await template();await register(b,true,r.phone);const values=await Promise.all([run(a),run(b)]);expect(values.map(x=>x.state).sort()).toEqual(['created','overlap']);expect((await totals(a)).tasks+(await totals(b)).tasks).toBe(1);});
it('生产Notion新页/已管理页两条真实SQL在queued owner上合法，混入执行result仍拒',async()=>{
 const id=await template();await register(id);const {task}=await run(id);
 await pool.query("UPDATE tasks SET notion_id=$2, notion_props = COALESCE(notion_props,'{}'::jsonb) || jsonb_build_object('pushed_status', $3::text, 'pushed_project', $4::text), notion_synced_at=NOW() WHERE id=$1",[task.id,randomUUID(),'queued','']);
 await pool.query("UPDATE tasks SET notion_props = COALESCE(notion_props,'{}'::jsonb) || jsonb_build_object('pushed_status', $2::text, 'pushed_project', $3::text), notion_synced_at=NOW() WHERE id=$1",[task.id,'queued','']);
 const row=(await pool.query('SELECT notion_id,notion_synced_at,notion_props FROM tasks WHERE id=$1',[task.id])).rows[0];expect(row.notion_id).toBeTruthy();expect(row.notion_synced_at).toBeInstanceOf(Date);expect(row.notion_props.pushed_status).toBe('queued');
 await expect(pool.query("UPDATE tasks SET notion_props='{}',notion_synced_at=now(),result='{}' WHERE id=$1",[task.id])).rejects.toThrow('phone_scheduled_task_managed');
});

it('517不回填或改动真508已leased历史，旧guard和未知占位保留',async()=>{expect(legacyAfter).toEqual(legacyBefore);expect((await pool.query('SELECT * FROM phone_task_owners WHERE task_id=$1',[legacyBefore.task.id])).rows).toEqual([]);await expect(pool.query("UPDATE tasks SET status='completed' WHERE id=$1",[legacyBefore.task.id])).rejects.toThrow('phone_task_managed');const id=await template();await register(id,true,phone);expect((await run(id)).state).toBe('overlap');expect((await totals(id)).tasks).toBe(0);});
it('真实CAS阶段阻塞跨过登记期限，COMMIT必须再次拒绝且完整回滚',async()=>{
 const id=await template();const r=await register(id);await store.setPhoneScheduleState(pool,{registrationId:r.id,revision:Number(r.revision),state:'active',expiresAt:new Date(Date.now()+1000)},auth);
 await pool.query(`CREATE FUNCTION fixture_c7_expiry() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id='${id}'::uuid THEN PERFORM pg_sleep(1.5); END IF;RETURN NEW;END $$;CREATE TRIGGER fixture_c7_expiry BEFORE UPDATE ON recurring_tasks FOR EACH ROW EXECUTE FUNCTION fixture_c7_expiry()`);
 try{await expect(run(id)).rejects.toThrow('phone_schedule_owner_required');expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});}finally{await pool.query('DROP TRIGGER fixture_c7_expiry ON recurring_tasks;DROP FUNCTION fixture_c7_expiry()');}
});
it('本地真实迁移只在scratch及私有schema，CI也固定schema隔离',async()=>{
 const row=(await pool.query('SELECT current_database() database,current_schema() schema')).rows[0];
 expect(row.database).toBe(DB_DEFAULTS.database);expect(row.schema).toMatch(/^phone_schedule_[a-z0-9_]+$/);
 if(process.env.CI!=='true')expect(row.database).toBe('cecelia_scratch');
});
