import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {DB_DEFAULTS} from '../db-config.js';
import {importLegacyPolicy} from '../execution-directory/store.js';
import {LEGACY_BINDINGS} from '../execution-directory/legacy-policy.js';
import {PHONE_SCHEDULE_REGISTRY_AUTHORITY} from './task-authority.js';
const holder=vi.hoisted(()=>({pool:null}));
vi.mock('../db.js',()=>({default:{query:(...a)=>holder.pool.query(...a),connect:(...a)=>holder.pool.connect(...a)}}));
vi.mock('../task-updater.js',()=>({broadcastTaskState:vi.fn()}));
const dbName=`phone_schedule_${process.pid}_${randomUUID().replaceAll('-','')}`;
const admin=new pg.Client({...DB_DEFAULTS,database:'postgres'});
let pool,store;
const phone={machine_id:'xian-mac-m1',serial:`fixture-${process.pid}`,host:'xian-m1',profile:'fixture-profile',account_id:'fixture-account',action:'adb_get_state'};
const auth={registryAuthority:PHONE_SCHEDULE_REGISTRY_AUTHORITY};
const now=new Date();now.setSeconds(10,0);const due=new Date(now);due.setSeconds(0,0);
beforeAll(async()=>{
 await admin.connect();await admin.query(`CREATE DATABASE ${dbName}`);
 execFileSync(process.execPath,['src/migrate.js'],{cwd:fileURLToPath(new URL('../../',import.meta.url)),env:{...process.env,NODE_ENV:'test',DB_NAME:dbName,DB_HOST:DB_DEFAULTS.host,DB_PORT:String(DB_DEFAULTS.port),DB_USER:DB_DEFAULTS.user,DB_PASSWORD:DB_DEFAULTS.password},stdio:'pipe'});
 pool=new pg.Pool({...DB_DEFAULTS,database:dbName,max:8});holder.pool=pool;
 for(const [,id,name]of LEGACY_BINDINGS)await pool.query("INSERT INTO system_registry(id,type,name,status) VALUES($1,'machine',$2,'active') ON CONFLICT(id) DO NOTHING",[id,`C7 fixture ${name}`]);
 await importLegacyPolicy({pool,env:{FLEET_WORKER_XIAN_MAC_M1_URL:'http://fixture-m1:5231'}});
 await pool.query("INSERT INTO phone_registry(serial,nickname,host,profile,douyin_accounts,enabled) VALUES($1,'C7 fixture',$2,$3,$4,true)",[phone.serial,phone.host,phone.profile,JSON.stringify([{id:phone.account_id,current:true}])]);
 store=await import('./schedule-store.js');
},180000);
afterAll(async()=>{if(pool)await pool.end();await admin.query(`DROP DATABASE IF EXISTS ${dbName}`);await admin.end();},30000);
async function template(){const id=randomUUID();await pool.query("INSERT INTO recurring_tasks(id,title,task_type,cron_expression,recurrence_type,is_active,next_run_at,template) VALUES($1,'C7 fixture','device_job','* * * * *','cron',true,$2,$3)",[id,due,{timezone:'UTC',executor_kind:'phone-ssh-controller',phone_authority:true}]);return id;}
async function register(id,enable=true,sharedPhone=null){const pins=sharedPhone||{...phone,serial:`fixture-${id}`};await pool.query("INSERT INTO phone_registry(serial,nickname,host,profile,douyin_accounts,enabled) VALUES($1,'C7 fixture',$2,$3,$4,true) ON CONFLICT(serial) DO NOTHING",[pins.serial,pins.host,pins.profile,JSON.stringify([{id:pins.account_id,current:true}])]);const r=await store.registerPhoneSchedule(pool,{templateId:id,phone:pins,parentTaskId:null,expiresAt:new Date(Date.now()+120000)},auth);if(enable)await store.setPhoneScheduleState(pool,{registrationId:r.id,revision:Number(r.revision),state:'active'},auth);return r;}
async function run(id){return store.processPhoneScheduledSlot(pool,{templateId:id,now});}
async function totals(id){return (await pool.query(`SELECT (SELECT count(*)::int FROM phone_scheduled_slots WHERE template_id=$1) slots,(SELECT count(*)::int FROM phone_task_owners WHERE template_id=$1) owners,(SELECT count(*)::int FROM tasks WHERE payload->'phone_schedule'->>'template_id'=$1::text) tasks,(SELECT count(*)::int FROM work_routing_receipts WHERE source_id LIKE 'recurring:'||$1::text||':%') receipts`,[id])).rows[0];}
it('513真实迁移独立登记且默认注册为空',async()=>{expect((await pool.query("SELECT version FROM schema_version WHERE version IN ('507','508','510','511','512','513') ORDER BY version")).rows.map(r=>r.version)).toEqual(['507','508','510','511','512','513']);expect((await pool.query('SELECT count(*)::int n FROM phone_schedule_registrations')).rows[0].n).toBe(0);});
it('public旗标和伪造authority不能注册；内部初始inactive',async()=>{const id=await template();await expect(run(id)).rejects.toThrow('phone_schedule_unregistered');await expect(store.registerPhoneSchedule(pool,{templateId:id,phone,expiresAt:new Date(Date.now()+60000)},{registryAuthority:true})).rejects.toThrow('phone_schedule_registry_authority_required');expect((await register(id,false)).state).toBe('inactive');await expect(run(id)).rejects.toThrow('phone_schedule_inactive');expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});
it('并发真实连接同slot只有一task/receipt/slot/owner，重复读原task',async()=>{const id=await template();await register(id);const result=await Promise.all([run(id),run(id)]);expect(result.filter(r=>r.state==='created')).toHaveLength(1);expect(await totals(id)).toEqual({slots:1,owners:1,tasks:1,receipts:1});const t=(await pool.query("SELECT * FROM tasks WHERE payload->'phone_schedule'->>'template_id'=$1",[id])).rows[0];expect(t).toMatchObject({task_type:'device_job',executor_kind:'phone-ssh-controller',kind:'agent',status:'queued'});expect(t.payload.routing_receipt_id).toBeTruthy();await pool.query('UPDATE recurring_tasks SET next_run_at=$2 WHERE id=$1',[id,due]);expect((await run(id)).state).toBe('existing');expect(await totals(id)).toEqual({slots:1,owners:1,tasks:1,receipts:1});});
it('跨routerversion历史ordinary同source拒绝重绑',async()=>{const id=await template();await register(id);const {createTask}=await import('../actions.js');await pool.query(`CREATE FUNCTION fixture_c7_old_router() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.source_id LIKE 'recurring:${id}:%' THEN NEW.router_version:='fixture-old-version'; END IF;RETURN NEW;END $$;CREATE TRIGGER fixture_c7_old_router BEFORE INSERT ON work_routing_receipts FOR EACH ROW EXECUTE FUNCTION fixture_c7_old_router()`);const old=await createTask({db:pool,source:'scheduler',source_id:`recurring:${id}:${due.toISOString()}`,title:'old ordinary',task_type:'research',allow_unscoped:true,payload:{old:true}});await pool.query('DROP TRIGGER fixture_c7_old_router ON work_routing_receipts;DROP FUNCTION fixture_c7_old_router()');expect((await pool.query('SELECT router_version FROM work_routing_receipts WHERE task_id=$1',[old.task.id])).rows[0].router_version).toBe('fixture-old-version');await expect(run(id)).rejects.toThrow('phone_schedule_route_collision');expect((await pool.query('SELECT executor_kind FROM tasks WHERE id=$1',[old.task.id])).rows[0].executor_kind).toBe(null);expect((await totals(id)).slots).toBe(0);});
async function fault(id,table,column,message){await pool.query(`CREATE FUNCTION fixture_c7_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ${column} THEN RAISE EXCEPTION '${message}'; END IF;RETURN NEW;END $$;CREATE TRIGGER fixture_c7_fault BEFORE ${table==='recurring_tasks'?'UPDATE':'INSERT'} ON ${table} FOR EACH ROW EXECUTE FUNCTION fixture_c7_fault()`);await expect(run(id)).rejects.toThrow(message);expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});expect(new Date((await pool.query('SELECT next_run_at FROM recurring_tasks WHERE id=$1',[id])).rows[0].next_run_at)).toEqual(due);await pool.query(`DROP TRIGGER fixture_c7_fault ON ${table};DROP FUNCTION fixture_c7_fault()`);expect((await run(id)).state).toBe('created');}
it('next_run_at SQL失败全部回滚原slot可重试',async()=>{const id=await template();await register(id);await fault(id,'recurring_tasks',`NEW.id='${id}'::uuid`,'fixture_cas_fault');});
it('真实receipt SQL失败全部回滚原slot可重试',async()=>{const id=await template();await register(id);await fault(id,'work_routing_receipts',`NEW.source_id LIKE 'recurring:${id}:%'`,'fixture_receipt_fault');});
it('queued未dispatch也拒绝旧claim/finish/payload/执行者修改；人类metadata允许',async()=>{const id=await template();await register(id);const {task}=await run(id);for(const sql of ["status='in_progress'","status='completed',result='{}'","claimed_by='old',claimed_at=now()","executor_kind='headed-session'","payload=payload||'{\"evil\":true}'::jsonb"]){await expect(pool.query(`UPDATE tasks SET ${sql} WHERE id=$1`,[task.id])).rejects.toThrow('phone_scheduled_task_managed');}await pool.query("UPDATE tasks SET title='human',priority='P0',due_at=now(),notion_props='{\"human\":true}'::jsonb WHERE id=$1",[task.id]);expect((await pool.query('SELECT title FROM tasks WHERE id=$1',[task.id])).rows[0].title).toBe('human');await expect(pool.query("UPDATE tasks SET title='mixed',result='{}' WHERE id=$1",[task.id])).rejects.toThrow('phone_scheduled_task_managed');});
it('普通task原地变phone拒绝',async()=>{const {createTask}=await import('../actions.js');const r=await createTask({db:pool,title:'ordinary conversion',task_type:'research',allow_unscoped:true});await expect(pool.query("UPDATE tasks SET executor_kind='phone-ssh-controller' WHERE id=$1",[r.task.id])).rejects.toThrow('phone_schedule_insert_required');});
it('仅真实task/receipt无slot/owner的COMMIT被deferred guard拒绝',async()=>{const id=await template();const reg=await register(id);const c=await pool.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('cecelia.phone_schedule_admission',$1,true)",[`${reg.id}:${reg.revision}:${due.toISOString()}`]);const {createPhoneScheduledTask}=await import('./task-authority.js');await createPhoneScheduledTask({db:c,registration:{...reg,title:'fixture'},slot:due});await expect(c.query('COMMIT')).rejects.toThrow('phone_schedule_owner_required');}finally{await c.query('ROLLBACK');c.release();}expect(await totals(id)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});
it('pins/revision/owner/slot不能删改',async()=>{const id=await template();const reg=await register(id);const r=await run(id);await expect(pool.query("UPDATE phone_schedule_registrations SET phone=phone||'{\"host\":\"evil\"}' WHERE id=$1",[reg.id])).rejects.toThrow('phone_schedule_registry_managed');await expect(pool.query('DELETE FROM phone_task_owners WHERE task_id=$1',[r.task.id])).rejects.toThrow('phone_schedule_identity_immutable');await expect(pool.query("UPDATE phone_scheduled_slots SET slot=slot+interval '1 minute' WHERE template_id=$1",[id])).rejects.toThrow('phone_schedule_identity_immutable');});
it('模板变化、过期、真实phone pins变化拒建单',async()=>{const id=await template();await register(id);await pool.query("UPDATE recurring_tasks SET template=template||'{\"timezone\":\"Asia/Shanghai\"}' WHERE id=$1",[id]);await expect(run(id)).rejects.toThrow('phone_schedule_template_changed');const id2=await template();const r=await register(id2);await store.setPhoneScheduleState(pool,{registrationId:r.id,revision:Number(r.revision),state:'active',expiresAt:new Date(Date.now()-1)},auth);await expect(run(id2)).rejects.toThrow('phone_schedule_expired');const id3=await template();const reg3=await register(id3);await pool.query('UPDATE phone_registry SET enabled=false WHERE serial=$1',[reg3.phone.serial]);await expect(run(id3)).rejects.toThrow('phone_schedule_phone_changed');await pool.query('UPDATE phone_registry SET enabled=true WHERE serial=$1',[reg3.phone.serial]);});
it('上一slot未知占位不能叠单，不推进next_run_at',async()=>{const id=await template();await register(id);await run(id);const next=new Date(due.getTime()+60000);await pool.query('UPDATE recurring_tasks SET next_run_at=$2 WHERE id=$1',[id,next]);expect((await store.processPhoneScheduledSlot(pool,{templateId:id,now:new Date(next.getTime()+10000)})).state).toBe('overlap');expect((await totals(id)).tasks).toBe(1);expect(new Date((await pool.query('SELECT next_run_at FROM recurring_tasks WHERE id=$1',[id])).rows[0].next_run_at)).toEqual(next);});

it('不同模板同一真实phone未知owner不能叠单',async()=>{const a=await template();const r=await register(a);await run(a);const b=await template();await register(b,true,r.phone);expect((await run(b)).state).toBe('overlap');expect(await totals(b)).toEqual({slots:0,owners:0,tasks:0,receipts:0});});
