module.exports = {
  apps: [
    {
      name: 'cecelia-brain',
      script: 'server.js',
      cwd: '/Users/administrator/perfect21/cecelia/packages/brain',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 5221,
      },
      error_file: '/tmp/cecelia-brain-error.log',
      out_file: '/tmp/cecelia-brain-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_size: '50M',
      retain: 5,
    },
    {
      name: 'skill-eval-daemon',
      script: 'scripts/skill-eval-daemon.js',
      cwd: '/Users/administrator/perfect21/cecelia/packages/brain',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        BRAIN_BASE_URL: 'http://localhost:5221',
        CLAUDE_BIN: '/opt/homebrew/bin/claude',
        CLAUDE_CONFIG_DIR: '/Users/administrator/.claude-account2',
        EVAL_PROMPT_PATH: '/Users/administrator/perfect21/skill-eval-formb-assets/eval-prompt.txt',
        EVAL_POLL_INTERVAL_MS: '10000',
        EVAL_STUCK_TIMEOUT_MINUTES: '15',
      },
      error_file: '/tmp/skill-eval-daemon-error.log',
      out_file: '/tmp/skill-eval-daemon-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_size: '50M',
      retain: 5,
    },
  ],
};
