import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: [
      'src/**/*.{test,spec}.?(c|m)[jt]s?(x)',
      '../../tests/packages/brain/**/*.{test,spec}.?(c|m)[jt]s?(x)',
    ],
    // 以下测试需要真实 PostgreSQL 连接或有其他 CI 环境 pre-existing 失败
    // brain-unit 跑纯单元测试（有 vi.mock('db.js') 的），集成测试走 brain-integration
    exclude: [
      // DB 集成测试（pool.query 直连，beforeAll import pool）
      'src/__tests__/actions-dedup.test.js',
      'src/__tests__/actions-goal-validation.test.js',
      'src/__tests__/actions-initiative-orchestration.test.js',
      'src/__tests__/alertness-actions.test.js',
      'src/__tests__/area-scheduler.test.js',
      'src/__tests__/blocks.test.js',
      'src/__tests__/capabilities-api.test.js',
      'src/__tests__/capability-scanner.test.js',
      'src/__tests__/code-review-trigger.test.js',
      'src/__tests__/consolidation.test.js',
      'src/__tests__/content-pipeline-orphan.test.ts',
      'src/__tests__/contract-scan-scheduler.test.js',
      'src/__tests__/cortex-dedup-persist.test.js',
      'src/__tests__/cortex-memory.test.js',
      'src/__tests__/cortex-quality-feedback.test.js',
      'src/__tests__/cortex-quality.test.js',
      'src/__tests__/cortex-rca.test.js',
      'src/__tests__/cortex.test.js',
      'src/__tests__/daily-publish-scheduler.test.js',
      'src/__tests__/daily-review-scheduler.test.js',
      'src/__tests__/decisions-context.test.js',
      'src/__tests__/dept-heartbeat.test.js',
      'src/__tests__/desire-feedback.test.js',
      'src/__tests__/desire-suggestions.test.js',
      'src/__tests__/emotion-layer.test.js',
      'src/__tests__/evolution-scanner.test.js',
      'src/__tests__/evolution-synthesizer.test.js',
      'src/__tests__/execution-strategy-session-kr-link.test.js',
      'src/__tests__/executor-retry-strategy.test.js',
      'src/__tests__/fact-extractor.test.js',
      'src/__tests__/harness-sprint-loop.test.js',
      'src/__tests__/health-monitor.test.js',
      'src/__tests__/initiative-closer.test.js',
      'src/__tests__/initiative-completion.test.js',
      'src/__tests__/initiative-orchestration-migration.test.js',
      'src/__tests__/initiative-queue.test.js',
      'src/__tests__/intent-match.test.js',
      'src/__tests__/intent.test.js',
      'src/__tests__/kr-progress.test.js',
      'src/__tests__/kr-verifier.test.js',
      'src/__tests__/learning-effectiveness.test.js',
      'src/__tests__/learning-search.test.js',
      'src/__tests__/learning.test.js',
      'src/__tests__/memory-capabilities-search.test.js',
      'src/__tests__/migration-015.test.js',
      'src/__tests__/migration-016.test.js',
      'src/__tests__/migration-018.test.js',
      'src/__tests__/migration-030.test.js',
      'src/__tests__/migration-041.test.js',
      'src/__tests__/migrations-087-suggestions.test.js',
      'src/__tests__/model-profile.test.js',
      'src/__tests__/model-registry.test.js',
      'src/__tests__/notebook-feeder.test.js',
      'src/__tests__/okr-closer.test.js',
      'src/__tests__/pending-conversations.test.js',
      'src/__tests__/person-model.test.js',
      'src/__tests__/planner-domain-routing.test.js',
      'src/__tests__/planner-initiative-plan.test.js',
      'src/__tests__/planner-learning-penalty.test.js',
      'src/__tests__/planner.test.js',
      'src/__tests__/quarantine-auto-release.test.js',
      'src/__tests__/quarantine-classification.test.js',
      'src/__tests__/quarantine-systemic.test.js',
      'src/__tests__/quota-exhausted-no-quarantine.test.js',
      'src/__tests__/quota-exhausted.test.js',
      'src/__tests__/resolve-repo-path.test.js',
      'src/__tests__/routes/memory.test.js',
      'src/__tests__/rumination-dedup.test.js',
      'src/__tests__/rumination-scheduler.test.js',
      'src/__tests__/self-drive.test.js',
      'src/__tests__/services/memory-service.test.js',
      'src/__tests__/startup-recovery.test.js',
      'src/__tests__/stats.test.js',
      'src/__tests__/suggestion-integration.test.js',
      'src/__tests__/suggestion-triage.test.js',
      'src/__tests__/task-generator-dedup.test.js',
      'src/__tests__/task-generator-scheduler.test.js',
      'src/__tests__/task-websocket.test.js',
      'src/__tests__/tasks-feedback.test.js',
      'src/__tests__/tasks-status.test.js',
      'src/__tests__/tick-codex-immune.test.js',
      'src/__tests__/tick-dispatch-scope-decomposing.test.js',
      'src/__tests__/tick-drain.test.js',
      'src/__tests__/tick-kr-decomp.test.js',
      'src/__tests__/tick-layer2-health.test.js',
      'src/__tests__/tick-rampup.test.js',
      'src/__tests__/tick-watchdog-quarantine.test.js',
      'src/__tests__/topic-selection-scheduler.test.js',
      'src/__tests__/watchdog-quarantine-race.test.js',
      'src/__tests__/watchdog.test.js',
      'src/__tests__/zombie-cleaner.test.js',
      // Mock 不完整或代码逻辑变更导致失败（pre-existing issue）
      'src/__tests__/content-pipeline-executors.test.js',
      'src/__tests__/content-pipeline-llm.test.js',
      'src/__tests__/content-pipeline-error-message.test.js',
      'src/__tests__/executor-startup-sync.test.js',
      'src/__tests__/startup-sync.test.js',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html', 'json', 'json-summary'],
      reportsDirectory: './coverage',
      include: [
        'src/**/*.js'
      ],
      exclude: [
        'src/**/*.test.js',
        'src/__tests__/**',
        'node_modules/**',
        'coverage/**'
      ],
      thresholds: {
        statements: 75,
        branches: 75,
        functions: 80,
        lines: 75,
        perFile: false
      },
      // Specific files we're tracking closely
      reportOnFailure: true,
      all: true,
      clean: true
    },
    testTimeout: 30000,
    hookTimeout: 30000,
    teardownTimeout: 30000,
    isolate: true,    // isolate:true — 每个测试文件独立模块注册表，消除跨文件 mock 污染
    pool: 'threads',
    poolOptions: {
      threads: {
        minThreads: 1,
        maxThreads: 2   // threads 模式共享内存（不 fork），内存效率远高于 forks，避免 ubuntu-latest OOM
      }
    }
  }
});
