-- Migration 115: system_reports table
-- Stores periodic system reports generated by Cortex (e.g., 48h summaries)
CREATE TABLE IF NOT EXISTS system_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type VARCHAR(50) NOT NULL DEFAULT '48h_summary',
  content TEXT NOT NULL,
  stats JSONB NOT NULL DEFAULT '{}',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for querying latest report by type
CREATE INDEX IF NOT EXISTS idx_system_reports_type_generated
  ON system_reports (report_type, generated_at DESC);

INSERT INTO schema_version (version, description)
VALUES ('115', 'system_reports')
ON CONFLICT (version) DO NOTHING;
